<a href="https://colab.research.google.com/github/macmacmccann/Ai_Beginner/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# Scalars
scalar = torch.tensor([7, 7])
scalar

tensor(7)

In [ ]:
# Getting tensor as python int

scalar.item()

In [ ]:
# Vectors
vector = torch.tensor([7,7] )
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
# Matrix
# Vec Scal And Matrix are all tensors - anything you input a number into is

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:

MATRIX.ndim
MATRIX[1]
MATRIX.shape # Look up you can see it is 2 arrays with 2 things


torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim
TENSOR.shape

# Dimensions of tensors are a valued concept - can you understand this answer? You have to be able to
#

torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way that nerual networks learn is that They start off with tensord full of rnadom numbers and then adjust those random numbers to better represent data

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

1.   https://pytorch.org/docs/stable/generated/torch.rand.html



In [ ]:
# Create a rnadom tensor size of 3,4

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9961, 0.1563, 0.6759, 0.5307],
        [0.1143, 0.0097, 0.9873, 0.7175],
        [0.9742, 0.1864, 0.4468, 0.8407]])

In [ ]:
random_tensor.ndim


2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similiar  shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width,colour channgel ( rgb)

random_image_size_tensor.ndim, random_image_size_tensor.shape



(3, torch.Size([224, 224, 3]))

In [ ]:
torch.rand(3,3)

tensor([[0.7923, 0.3566, 0.7077],
        [0.8810, 0.6053, 0.6237],
        [0.2936, 0.8717, 0.4234]])

### Zeros and Ones


In [ ]:
zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Create a range of tensor and tensors-like

torce.arange(1,10)


In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 6.0], dtype = None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 6.])

### Precision and Computing

32-bit- floating point is if you want precision if the precision matters towards the final calucation - smaller ones take up less memeory and are faaster to compute
See the documentation for precision and data types
so much errod come up with wrong datatype casting
https://pytorch.org/docs/stable/tensors.html

# Manipulating Tensors (tensor operations)

Tensor operation include:

* Addition
*Subtraction
*Multiplication
*Division
*MAtrix Multipilcation


In [ ]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

### Matrix Multipucation
2 ways to perform mult in neural networks

1, element wise mult
2, matrix mult ( dot product = heavy fullstop vs x )

https://www.mathsisfun.com/algebra/matrix-multiplying.html


1. Matrix inner dimensions must match . Look at the math to know that you can make that error .

Dimensions like

  3,2 @ 3,2 wont work
  2,3 @ 3,2 will work -> 2,2
  3,2 @ 2,3 will work -> 2,2


http://matrixmultiplication.xyz/

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#Matrix Mulication option one

torch.matmul (tensor,tensor)

tensor(14)

In [ ]:
#Matrix Mulication option two

tensor @ tensor


tensor(14)

In [ ]:
tensor_A = torch.tensor ([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor ([[1,2],[3,4],[5,6]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul - shorter to write



RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B, tensor_B.shape



(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([3, 2]))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes and input tensor to a defined shape
* Veiw - reutrn a view of an input tensor of certain shape but kepp the same memory as the orginal tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
* Squeeze - removes all "l" dimnesions from a tensor
* Unsqueeze - add dimension to target tensor
* Permute - Return a view of the input with dimensionspermuted (swapped) in a certain way  

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Reshape to a new variable

x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x2 = torch.arange(1., 11.)
x2, x2.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x2_reshaped = x2.reshape(5,2)
x2_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# Change the view

z = x.view(1, 10)
z, z.shape


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# Stack tensors on top of eachother
# Connacates a sequences of tensors along a new dimension

x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
torch.squeeze - removes all single target dimensions from the target %tensorflow_version


torch.squeeze - removes all single target dimensions from the target tensor

torch unsqueeze - adds an extra dimension with unsqueeze



torch.permute - re- arranges the dimensions fo a target tensor in a specified order.

In [ ]:
x_first = torch.rand(size=(244, 244, 3)) # (height, width, colour_channels)

# Permute the orginal tensor to rearrange the axis (or dim) order

x_permuted = x_first.permute(2, 0 , 1) # shifts axis 0-> 1,  1 -> 2, 2 -> 0 remember there is no 3

print(f"Previous Shape: {x_first.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous Shape: torch.Size([244, 244, 3])
New Shape: torch.Size([3, 244, 244])


Indexing Tensors



In [1]:
import torch


In [4]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [5]:
# Lets index on our new tensor

# 0 is 1 rememeber that about indexing - numbering doesnt start from 1 theyre is a zeropth item

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
# Index on the middle brakcet

x[0,0]

tensor([1, 2, 3])

In [7]:
# Index on the most inner bracket (last dimension)

x[0,0,0]

tensor(1)

NumPy is a popular scientific python numerical computing library

pytorch can interact with it

they both have dif data types default so you have to change one -   numpy is float64  and torch.float32

In [8]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reporudcability (trying to take random out of random . )

in short how a nueral network network learns:

start with random numbers -> tensor operations -> update random numbers to try to make them better represenations of the data ,again,again,again

to reduce the randomness in neural networkls ccomes to the concept of a random seed.

it flavours the randomness


In [11]:
import torch

# Random seed

# random seed initaliases the generic import random - but saves the random numbers to the variable
#you use torch.manual_seed(name of seed )

random_seed = 42

torch.manual_seed(random_seed)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A== random_tensor_B )

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


https://pytorch.org/docs/stable/notes/randomness.html