<a href="https://colab.research.google.com/github/macmacmccann/Ai_Beginner/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# Scalars
scalar = torch.tensor([7, 7])
scalar

tensor(7)

In [ ]:
# Getting tensor as python int

scalar.item()

In [ ]:
# Vectors
vector = torch.tensor([7,7] )
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
# Matrix
# Vec Scal And Matrix are all tensors - anything you input a number into is

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:

MATRIX.ndim
MATRIX[1]
MATRIX.shape # Look up you can see it is 2 arrays with 2 things


torch.Size([2, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim
TENSOR.shape

# Dimensions of tensors are a valued concept - can you understand this answer? You have to be able to
#

torch.Size([1, 3, 3])

### Random tensors

Random tensors are important because the way that nerual networks learn is that They start off with tensord full of rnadom numbers and then adjust those random numbers to better represent data

start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

1.   https://pytorch.org/docs/stable/generated/torch.rand.html



In [ ]:
# Create a rnadom tensor size of 3,4

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9961, 0.1563, 0.6759, 0.5307],
        [0.1143, 0.0097, 0.9873, 0.7175],
        [0.9742, 0.1864, 0.4468, 0.8407]])

In [ ]:
random_tensor.ndim


2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similiar  shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height,width,colour channgel ( rgb)

random_image_size_tensor.ndim, random_image_size_tensor.shape



(3, torch.Size([224, 224, 3]))

In [ ]:
torch.rand(3,3)

tensor([[0.7923, 0.3566, 0.7077],
        [0.8810, 0.6053, 0.6237],
        [0.2936, 0.8717, 0.4234]])

### Zeros and Ones


In [ ]:
zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Create a range of tensor and tensors-like

torce.arange(1,10)


In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])